server:
  port: 8088
spring:
  kafka:
    bootstrap-servers: kafka3:9092,kafka4:9092,kafka5:9092,kafka6:9092,kafka7:9092
    username: admin
    password: admin-secret
  datasource:
    url: jdbc:mysql://mysql:3306/airport_geniusIOT?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true
    #    url: jdbc:mysql://localhost:3306/geniusiot?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true
    username: root
    password: zydl2019
    #    password: Zhengyuan123!
    #    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    cluster:
      # 各 Redis 节点信息
      nodes: redis1:6379,redis2:6379,redis3:6379
      # 执行命令超时时间
      command-timeout: 60000
      # 重试次数
      max-attempts: 5
      # 跨集群执行命令时要遵循的最大重定向数量
      max-redirects: 3
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 16
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
      test-on-borrow: true
      timeout: 60000
    password: zydl2020
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.zydl.common.mapper: debug
mqtt:
  port: 1883
websocket:
  port: 8888
#异步线程池
async:
  executor:
    thread:
      core_pool_size: 1
      max_pool_size: 4
      queue_capacity: 100
      keep_alive_seconds: 60